FROM nginx:latest

COPY mysite_nginx.conf /etc/nginx/conf.d/mysite_nginx.conf

# COPY mysite_nginx.conf /etc/nginx/sites-available/
# RUN mkdir -p /etc/nginx/sites-enabled/ \
# && ln -s /etc/ngnix/sites-available/mysite_nginx.conf /etc/nginx/sites-enabled/

#CMD ["nginx", "-g", "daemon off;"]
